libmei: cast fwsts_num to off_t to suppress warning
Cast fwsts_num to off_t to prevent compiler warning on 32 bit arch.
The compiler detects sign-conversion due to possible
multiplication overflow.
Since the numbers are small and verified cast is enough to suppress
the warning.

src/linux/mei.c:245:52: error: conversion to ‘long int’ from ‘uint32_t’
  {aka ‘unsigned int’}  may change the sign of the result
  [-Werror=sign-conversion]
len = pread(fd, line, FWSTS_LEN, fwsts_num * FWSTS_LEN);

Signed-off-by: Tomas Winkler <tomas.winkler@intel.com>